#!/bin/sh

ACTION=start
PID_PATH=/tmp/remote_i3wm_ws.pid

ri3wmws_stop() {
    if [ -f "$PID_PATH" ]; then
        PID=$(cat "$PID_PATH")

        if [ -n "$PID" -a $(egrep "^[0-9]+$" "$PID_PATH") ]; then
            kill -9 "$PID"
            rm "$PID_PATH"
            printf "Server stopped\n"
        else
            printf "Server not started\n"
        fi
    else
        printf "Server not started\n"
    fi
}

ri3wmws_start() {
    if [ -f "$PID_PATH" ]; then
        printf "Server already started\n"
    else
        php src/resource/server.php "$REMOTE_I3WM_WS_OPTIONS" &
        PID=$!

        printf $PID > "$PID_PATH"
        chmod 600 "$PID_PATH"
        printf "Server is running\n"
    fi
}

ri3wmws_restart() {
    ri3wmws_stop
    ri3wmws_start
}

cd "$(dirname "$(realpath "$0")")"

case "$1" in
    start) ri3wmws_start;;
    restart) ri3wmws_restart;;
    stop) ri3wmws_stop;;
esac;
